# Generated by Django 4.2.7 on 2024-02-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_mymodel_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key',
            field=models.BinaryField(null=True),
        ),
    ]
